# This workflow will build a Java project with Maven

name: CI/CD

on:
  push:
    branches: 
      - main

jobs:   
  build-and-publish:
    name: Build and publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build project
        run: mvn -B package --file pom.xml
      - name: Docker login
        run: docker login ghcr.io --username $GITHUB_ACTOR --password ${{ secrets.PAT }}
      - name: Build Docker image
        run: docker build . -t ${{ secrets.PACKAGE }}
      - name: Publish Docker image
        run: docker push ${{ secrets.PACKAGE }}
      - name: Login on server
        run: |
          mkdir -p ~/.ssh/
          echo "${{ secrets.RSA }}" > ~/.ssh/rsa
          chmod 600 ~/.ssh/rsa
          ssh-keyscan -H ${{ secrets.SERVER }} > ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts
      - name: Deploy
        run: ssh -i ~/.ssh/rsa ${{ secrets.USERNAME }}@${{ secrets.SERVER }} "bash ~/deploy.sh $GITHUB_ACTOR ${{ secrets.PAT }} ${{ secrets.PACKAGE }}"
